### ISSUE TITLE
[BUG] Remove text doesn't work

### ISSUE THREAD

**Issue by dddfault** [RustyMods/Messenger#1]
Hi Rusty. I just tried your new mod here. And seems like the remove button to clear the logs seems didn't work and it break the pop-up and the text crossfade animation. I can provide you more detailed feedback and logs if you need it

**Comment by dddfault** [comment]
Looks like that I set the duration bit too long for 2 notification. so far everything's working except the remove button

**Comment by RustyMods** [comment]
what are you trying to remove ? it simply removes the known texts, not logs. are there errors ? if a topic isn't chosen, it shouldnt do anything

**Comment by dddfault** [comment]
> what are you trying to remove ? it simply removes the known texts, not logs. are there errors ? if a topic isn't chosen, it shouldnt do anything

My bad, I didn't really catch that tho. I was trying this mod with new character with blank known texts, i thought that remove or deletes the logs.
